# Generated by Django 4.2.11 on 2024-05-03 10:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kks_reestr_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KksCodeSystemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kks_system_abr', models.CharField(help_text='Обязательно 3 символа', max_length=3, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Код системы')),
                ('kks_system_description', models.CharField(max_length=150, verbose_name='Описание')),
                ('kks_system_visible', models.BooleanField(default=True, verbose_name='Видимость')),
            ],
            options={
                'verbose_name': 'kks код системы',
                'verbose_name_plural': 'kks коды систем',
            },
        ),
        migrations.CreateModel(
            name='KksExecutionConstructionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kks_exec_construction', models.IntegerField(help_text='0-5', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Код типа конструкции')),
                ('kks_exec_construction_description', models.CharField(max_length=100, verbose_name='Описание типа конструкции')),
            ],
            options={
                'verbose_name': 'kks код исполнения конструкции',
                'verbose_name_plural': 'kks коды исполнения конструкций',
            },
        ),
        migrations.CreateModel(
            name='KksHighMarkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kks_high_mark', models.CharField(help_text='Код высотной отметки по таблице 4.12', max_length=2, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Код высотной отметки')),
                ('kks_high_mark_description', models.CharField(max_length=100, verbose_name='Область высотны отметок')),
            ],
            options={
                'verbose_name': 'kks код высотной отметки',
                'verbose_name_plural': 'kks коды высотных отметок',
            },
        ),
        migrations.CreateModel(
            name='KksObjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kks_object_abr', models.CharField(help_text='Сектор 1', max_length=4, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='KKS код объекта сокращенно')),
                ('kks_object_full_name', models.CharField(max_length=100, verbose_name='KKS код объекта полностью')),
                ('kks_object_show', models.BooleanField(default=True, help_text='Отображение в списках выбора, при генерации нового kks кода', verbose_name='Видимость в списках')),
            ],
            options={
                'verbose_name': 'kks объекта',
                'verbose_name_plural': 'kks объектов',
            },
        ),
        migrations.CreateModel(
            name='KksOrganizationCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kks_org_code', models.IntegerField(verbose_name='Код организации')),
                ('kks_org_description', models.CharField(max_length=150, verbose_name='Наименование организации')),
                ('kks_org_visible', models.BooleanField(default=True, verbose_name='Видимость')),
                ('kks_org_object', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='kks_reestr_app.kksobjectmodel', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Kks код организации',
                'verbose_name_plural': 'Kks коды организаций',
            },
        ),
        migrations.CreateModel(
            name='KksSector5Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kks_sector5_value', models.CharField(help_text='6 символов', max_length=6, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Значение сектора 5')),
            ],
            options={
                'verbose_name': 'значение сектора 5',
                'verbose_name_plural': 'значения сектора 5',
            },
        ),
        migrations.CreateModel(
            name='KksSector6Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kks_sector6_value', models.CharField(help_text='Максимум 5 символов', max_length=5, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Значение сектора 5')),
            ],
            options={
                'verbose_name': 'значение сектора 6',
                'verbose_name_plural': 'значения сектора 6',
            },
        ),
        migrations.CreateModel(
            name='KksStageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kks_stage_letter', models.CharField(help_text='Код этапа (стадии) жизненного цикла в соответствии с таблицаей А.1 приложения А (сектор 2)', max_length=1, verbose_name='Буквенное обозначение этапа (стадии)')),
                ('kks_stage_description', models.CharField(max_length=35, verbose_name='Описание кода этапа (стадии)')),
            ],
            options={
                'verbose_name': 'kks код этапа',
                'verbose_name_plural': 'kks коды этапов',
            },
        ),
        migrations.CreateModel(
            name='KksTechnicalSpecialtyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kks_tech_speciality', models.CharField(help_text='3 цифры, согласно таблице В.1 приложения В', max_length=3, verbose_name='Код технической специальности')),
                ('kks_tech_speciality_description', models.CharField(max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'kks код технической специальности',
                'verbose_name_plural': 'kks коды технических специальностей',
            },
        ),
        migrations.CreateModel(
            name='KksTypeBuildingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kks_type_building_code', models.CharField(max_length=1, verbose_name='Код KKS типа здания (сектора 4)')),
                ('kks_type_building_description', models.CharField(max_length=150, verbose_name='Наименование организации')),
            ],
            options={
                'verbose_name': 'kks код типа здания',
                'verbose_name_plural': 'kks коды типов зданий',
            },
        ),
        migrations.CreateModel(
            name='KksTypeConstructionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kks_type_construction', models.IntegerField(help_text='0-8', validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(0)], verbose_name='Код типа конструкции')),
                ('kks_type_construction_description', models.CharField(max_length=100, verbose_name='Описание типа конструкции')),
            ],
            options={
                'verbose_name': 'kks код типа конструкции',
                'verbose_name_plural': 'kks коды типов конструкций',
            },
        ),
        migrations.CreateModel(
            name='KksTypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kks_type_doc', models.CharField(help_text='2 буквы, согласно таблице Г.1 приложения Г', max_length=2, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Код вида документа')),
                ('kks_type_doc_description', models.CharField(max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'kks код вида документа',
                'verbose_name_plural': 'kks коды видов документов',
            },
        ),
        migrations.CreateModel(
            name='KksStageObjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kks_stage_object_visible', models.BooleanField(default=True, verbose_name='Видимость')),
                ('kks_object', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='kks_reestr_app.kksobjectmodel', verbose_name='Объект')),
                ('kks_stage', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='kks_reestr_app.kksstagemodel', verbose_name='Стадия')),
            ],
            options={
                'verbose_name': 'этап у объекта',
                'verbose_name_plural': 'этапы у объектов',
            },
        ),
        migrations.CreateModel(
            name='KksOrganizationCodeObjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kks_organization_code_object_visible', models.BooleanField(default=True, verbose_name='Видимость')),
                ('kks_object', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='kks_reestr_app.kksobjectmodel', verbose_name='Объект')),
                ('kks_organization_code', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='kks_reestr_app.kksorganizationcodemodel', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'организация относящаяся к объекту',
                'verbose_name_plural': 'организации относящиеся к объектам',
            },
        ),
        migrations.CreateModel(
            name='KksCodeSystemOrganizationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kks_system_organization_visible', models.BooleanField(default=True, verbose_name='Видимость')),
                ('kks_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kks_reestr_app.kksobjectmodel', verbose_name='Объект')),
                ('kks_system', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='kks_reestr_app.kkscodesystemmodel', verbose_name='Код системы')),
            ],
            options={
                'verbose_name': 'kks код системы у объекта',
                'verbose_name_plural': 'kks коды систем у объектов',
            },
        ),
        migrations.CreateModel(
            name='KksCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.IntegerField(verbose_name='Порядковый номер')),
                ('status', models.IntegerField(choices=[(0, 'Аннулирован'), (1, 'Актуален')], default=1, verbose_name='Статус номера')),
                ('text', models.CharField(max_length=37, verbose_name='Kks код')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='kks_reestr_app.employeemodel', verbose_name='Кто взял номер')),
                ('object', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='kks_reestr_app.kksobjectmodel', verbose_name='Объект')),
                ('organization', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='kks_reestr_app.kksorganizationcodeobjectmodel', verbose_name='Организация')),
                ('sector5', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='kks_reestr_app.kkssector5model', verbose_name='Сектор 5')),
                ('sector6', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='kks_reestr_app.kkssector6model', verbose_name='Сектор 6')),
                ('stage', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='kks_reestr_app.kksstageobjectmodel', verbose_name='Стадия')),
                ('tech_speciality', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='kks_reestr_app.kkstechnicalspecialtymodel', verbose_name='Код технической специальности')),
                ('type_building', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='kks_reestr_app.kkstypebuildingmodel', verbose_name='Тип здания')),
                ('type_doc', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='kks_reestr_app.kkstypedocument', verbose_name='Код вида документа')),
            ],
            options={
                'verbose_name': 'kks код',
                'verbose_name_plural': 'kks коды',
            },
        ),
        migrations.CreateModel(
            name='KksChangesHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата изменения')),
                ('previous_value', models.CharField(max_length=37, verbose_name='Старое значение')),
                ('new_value', models.CharField(max_length=37, verbose_name='Старое значение')),
                ('author_of_change', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kks_reestr_app.employeemodel', verbose_name='Автор изменения')),
                ('kks_code', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kks_reestr_app.kkscodemodel', verbose_name='Kks код')),
            ],
            options={
                'verbose_name': 'история изменения',
                'verbose_name_plural': 'история изменений',
            },
        ),
        migrations.CreateModel(
            name='KksBuildingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kks_building_abr', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Kks код здания')),
                ('kks_building_description', models.CharField(max_length=150, verbose_name='Описание здания')),
                ('kks_object', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='kks_reestr_app.kksobjectmodel', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'kks код здания',
                'verbose_name_plural': 'kks коды зданий',
            },
        ),
    ]
