# Generated by Django 4.2.11 on 2024-05-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kks_reestr_app', '0002_kkscodesystemmodel_kksexecutionconstructionmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kksbuildingmodel',
            name='kks_building_visible',
            field=models.BooleanField(default=True, verbose_name='Видимость'),
        ),
    ]
