# Generated by Django 4.2.11 on 2024-05-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kks_reestr_app', '0003_kksbuildingmodel_kks_building_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kksorganizationcodemodel',
            name='kks_org_object',
        ),
    ]
