# Generated by Django 4.2.11 on 2024-05-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kks_reestr_app', '0005_alter_kksorganizationcodemodel_kks_org_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kkscodesystemorganizationmodel',
            options={'verbose_name': 'код системы у объекта', 'verbose_name_plural': 'коды систем у объектов'},
        ),
        migrations.AlterField(
            model_name='kkstechnicalspecialtymodel',
            name='kks_tech_speciality_description',
            field=models.CharField(max_length=250, verbose_name='Описание'),
        ),
    ]
