# Generated by Django 4.2.11 on 2024-05-03 12:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kks_reestr_app', '0006_alter_kkscodesystemorganizationmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kksbuildingmodel',
            name='kks_object',
        ),
        migrations.AddField(
            model_name='kksbuildingmodel',
            name='kks_type_building',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='kks_reestr_app.kkstypebuildingmodel', verbose_name='Тип здания (сектор 4)'),
        ),
        migrations.AddField(
            model_name='kkstypebuildingmodel',
            name='kks_object',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='kks_reestr_app.kksobjectmodel', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='kkstechnicalspecialtymodel',
            name='kks_tech_speciality',
            field=models.CharField(help_text='3 цифры, согласно таблице В.1 приложения В', max_length=3, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Код технической специальности'),
        ),
    ]
