# Generated by Django 4.2.11 on 2024-05-07 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kks_reestr_app', '0008_kksbuildingmodel_kks_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kkstechnicalspecialtymodel',
            name='kks_tech_speciality_construction',
            field=models.BooleanField(default=False, verbose_name='Конструкторская документация'),
        ),
        migrations.AddField(
            model_name='kkstechnicalspecialtymodel',
            name='kks_tech_speciality_show',
            field=models.BooleanField(default=True, verbose_name='Видимость'),
        ),
        migrations.AlterField(
            model_name='kkstechnicalspecialtymodel',
            name='kks_tech_speciality',
            field=models.CharField(help_text='3 цифр, согласно таблице В.1 приложения В, за исключением конструкторской документации', max_length=3, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Код технической специальности'),
        ),
    ]
