# Generated by Django 4.2.11 on 2024-05-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kks_reestr_app', '0011_kksthematicdirectionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kksthematicdirectionmodel',
            name='kks_thematic_direction_visible',
            field=models.BooleanField(default=True, verbose_name='Видимость'),
        ),
    ]
