# Generated by Django 4.2.11 on 2024-05-15 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kks_reestr_app', '0012_alter_kksthematicdirectionmodel_kks_thematic_direction_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kkssector6model',
            name='kks_sector6_value',
            field=models.CharField(help_text='Максимум 5 символов', max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Значение сектора 5'),
        ),
    ]
